cd /d C:\Program Files\AutoHotkey\Compiler
Ahk2Exe.exe /in AeroZoom_MouseL_x64.ahk /bin "Unicode 64-bit.bin"
Ahk2Exe.exe /in AeroZoom_MouseR_x64.ahk /bin "Unicode 64-bit.bin"
Ahk2Exe.exe /in AeroZoom_MouseM_x64.ahk /bin "Unicode 64-bit.bin"
Ahk2Exe.exe /in AeroZoom_MouseX1_x64.ahk /bin "Unicode 64-bit.bin"
Ahk2Exe.exe /in AeroZoom_MouseX2_x64.ahk /bin "Unicode 64-bit.bin"
Ahk2Exe.exe /in AeroZoom_Alt_x64.ahk /bin "Unicode 64-bit.bin"
Ahk2Exe.exe /in AeroZoom_Ctrl_x64.ahk /bin "Unicode 64-bit.bin"
Ahk2Exe.exe /in AeroZoom_Win_x64.ahk /bin "Unicode 64-bit.bin"
Ahk2Exe.exe /in AeroZoom_Shift_x64.ahk /bin "Unicode 64-bit.bin"
Ahk2Exe.exe /in AeroZoom_MouseL.ahk /bin "Unicode 32-bit.bin"
Ahk2Exe.exe /in AeroZoom_MouseR.ahk /bin "Unicode 32-bit.bin"
Ahk2Exe.exe /in AeroZoom_MouseM.ahk /bin "Unicode 32-bit.bin"
Ahk2Exe.exe /in AeroZoom_MouseX1.ahk /bin "Unicode 32-bit.bin"
Ahk2Exe.exe /in AeroZoom_MouseX2.ahk /bin "Unicode 32-bit.bin"
Ahk2Exe.exe /in AeroZoom_Alt.ahk /bin "Unicode 32-bit.bin"
Ahk2Exe.exe /in AeroZoom_Ctrl.ahk /bin "Unicode 32-bit.bin"
Ahk2Exe.exe /in AeroZoom_Win.ahk /bin "Unicode 32-bit.bin"
Ahk2Exe.exe /in AeroZoom_Shift.ahk /bin "Unicode 32-bit.bin"
pause